In [7]:
pip install scikit-learn

  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/5f/08/c66e99f06fb73f727c870172f0962c103262ac68839cc05234709b7b45c2/scikit_learn-1.3.0-cp38-cp38-win_amd64.whl.metadata
     ---------------------------------------- 0.0/42.2 MB ? eta -:--:--
     --------------------------------------- 0.0/42.2 MB 991.0 kB/s eta 0:00:43
     ---------------------------------------- 0.1/42.2 MB 1.3 MB/s eta 0:00:33
     ---------------------------------------- 0.2/42.2 MB 1.4 MB/s eta 0:00:30
     ---------------------------------------- 0.4/42.2 MB 2.2 MB/s eta 0:00:19
      --------------------------------------- 0.6/42.2 MB 2.7 MB/s eta 0:00:16
      --------------------------------------- 0.9/42.2 MB 3.2 MB/s eta 0:00:13
     - -------------------------------------- 1.1/42.2 MB 3.6 MB/s eta 0:00:12
     - -------------------------------------- 1.3/42.2 MB 3.6 MB/s eta 0:00:12
     - -------------------------------------- 1.6/42.2 MB 3.8 MB/s eta 0:00:11


In [24]:
import sklearn

In [25]:
from sklearn.datasets import load_iris
from sklearn.datasets import load_digits

In [26]:
import pandas as pd
import numpy as np

In [27]:
iris_dataset=load_iris()

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
iris_dataset['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [30]:
iris_dataset['data'][:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [31]:
iris_dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [32]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [33]:
X_train , X_test , y_train ,y_test=train_test_split(iris_dataset['data'],iris_dataset['target'],random_state=0)

In [34]:
print(y_test[:6])

[2 1 0 2 0 2]


In [37]:
from sklearn.neighbors import KNeighborsClassifier

In [38]:
iris_dataset['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [39]:
knn=KNeighborsClassifier(n_neighbors=5)

In [40]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [41]:
y=knn.predict(X_test)

In [42]:
print(np.mean(y==y_test))

0.9736842105263158
